language: java
sudo: true
dist: trusty
jdk: oraclejdk8
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
addons:
  apt:
    packages:
      - oracle-java8-installer
before_install:
  - chmod +x mvnw