INSERT INTO USER (ID, AUTHORITY, NAME, PASSWORD, USERNAME, USER, EMAIL, LAST_NAME, IS_VERIFIED) VALUES (1003, 4, 'Admin', '$2a$10$CVa8SXT7DjCDtgDbHYN3FOEewdXLCh2zrJkammFrc3W4LUzqKF3N6', 'admin', 'SYSADMIN', 'admin@admin.com', 'Admincic', 1);  
INSERT INTO SYSTEM_ADMIN (ID) VALUES (1003);

INSERT INTO USER (ID, AUTHORITY, NAME, PASSWORD, USERNAME, USER, EMAIL, LAST_NAME, IS_VERIFIED) VALUES (1000, 0, 'Petar', '$2a$10$CVa8SXT7DjCDtgDbHYN3FOEewdXLCh2zrJkammFrc3W4LUzqKF3N6', 'perica', 'REGUSER', 'pera@admin.com', 'Peric', 1);  
INSERT INTO REGISTRED_USER (ID, MEMBERSHIP_RANK) VALUES (1000, 1);

INSERT INTO USER (ID, AUTHORITY, NAME, PASSWORD, USERNAME, USER, EMAIL, LAST_NAME, IS_VERIFIED) VALUES (1020, 0, 'Marko', '$2a$10$CVa8SXT7DjCDtgDbHYN3FOEewdXLCh2zrJkammFrc3W4LUzqKF3N6', 'makica', 'REGUSER', 'markopaprika@gmail.com', 'Arambasic', 1);  
INSERT INTO REGISTRED_USER (ID, MEMBERSHIP_RANK) VALUES (1020, 1);

INSERT INTO USER (ID, AUTHORITY, NAME, PASSWORD, USERNAME, USER, EMAIL, LAST_NAME, IS_VERIFIED) VALUES (1001, 0, 'Mirko', '$2a$10$CVa8SXT7DjCDtgDbHYN3FOEewdXLCh2zrJkammFrc3W4LUzqKF3N6', 'mirkec', 'REGUSER', 'mirko@admin.com', 'Miric', 1);  
INSERT INTO REGISTRED_USER (ID, MEMBERSHIP_RANK) VALUES (1001, 1);

INSERT INTO USER (ID, AUTHORITY, NAME, PASSWORD, USERNAME, USER, EMAIL, LAST_NAME, IS_VERIFIED) VALUES (1002, 0, 'Ana', '$2a$10$CVa8SXT7DjCDtgDbHYN3FOEewdXLCh2zrJkammFrc3W4LUzqKF3N6', 'ancica', 'REGUSER', 'ana@admin.com', 'Ancic', 1);  
INSERT INTO REGISTRED_USER (ID, MEMBERSHIP_RANK) VALUES (1002, 2);

INSERT INTO FRIENDSHIP (ID, FRIEND_ONE_ID, FRIEND_TWO_ID, FIRENDSHIP_STATUS, OWNER_ID) VALUES (1001, 1002, 1000, 2, 1002);
INSERT INTO FRIENDSHIP (ID, FRIEND_ONE_ID, FRIEND_TWO_ID, FIRENDSHIP_STATUS, OWNER_ID) VALUES (1002, 1001, 1000, 0, 1001);

INSERT INTO FRIENDSHIP (ID, FRIEND_ONE_ID, FRIEND_TWO_ID, FIRENDSHIP_STATUS, OWNER_ID) VALUES (1003, 1000, 1002, 2, 1002);
INSERT INTO FRIENDSHIP (ID, FRIEND_ONE_ID, FRIEND_TWO_ID, FIRENDSHIP_STATUS, OWNER_ID) VALUES (1004, 1000, 1001, 0, 1001);

INSERT INTO LOCATION (ID, ADRESS, CODE, LAT, LNG) VALUES (1000, 'Qatar', 'QTR', 25.3548, 51.1839);
INSERT INTO COMPANY (DTYPE, ID, NAME, PROMTIVE_DESCRIPTION, RATE, LOCATION_ID, RATE_COUNT) VALUES ('AVIO', 1669, 'QATAR', 'We are amazing!', 470, 1000, 50);

INSERT INTO USER (ID, AUTHORITY, NAME, PASSWORD, USERNAME, USER, EMAIL, LAST_NAME, IS_VERIFIED, FIRST_LOGIN) VALUES (1010, 2, 'maki', '$2a$10$CVa8SXT7DjCDtgDbHYN3FOEewdXLCh2zrJkammFrc3W4LUzqKF3N6', 'maki', 'AVIOADMIN', 'maki@maki.com', 'Maki', 1, 1);  
INSERT INTO AVIO_ADMIN (ID, AVIO_ID) VALUES (1010, 1669);

INSERT INTO COMPANY_DESTINATIONS (AVIO_COMPANY_ID, DESTINATIONS_ID) VALUES (1669, 1000);

INSERT INTO LOCATION (ID, ADRESS, CODE, LAT, LNG) VALUES (2000, 'Paris', 'PAR', 48.864716, 2.349014);
INSERT INTO COMPANY (DTYPE, ID, NAME, PROMTIVE_DESCRIPTION, RATE, RATE_COUNT, LOCATION_ID) VALUES ('HOTEL', 6196, 'Hilton Paris', 'Sleep here!', 23, 5, 2000);
INSERT INTO LOCATION (ID, ADRESS, CODE, LAT, LNG) VALUES (3000, 'Futog', 'FUT', 45.240372, 19.711800);
INSERT INTO COMPANY (DTYPE, ID, NAME, PROMTIVE_DESCRIPTION, RATE, RATE_COUNT, LOCATION_ID) VALUES ('HOTEL', 3995, 'Kurjak', 'Rakija i lom!', 13, 4, 3000);

INSERT INTO USER (ID, AUTHORITY, NAME, PASSWORD, USERNAME, USER, EMAIL, LAST_NAME, IS_VERIFIED, FIRST_LOGIN) VALUES (1111, 1,'Dusan','$2a$10$CVa8SXT7DjCDtgDbHYN3FOEewdXLCh2zrJkammFrc3W4LUzqKF3N6','duki','HOTELADMIN','duki@duki.com','Marjanski',1,0);  
INSERT INTO HOTEL_ADMIN (ID, HOTEL_ID) VALUES (1111, 6196);

INSERT INTO ROOM (ID, ACTIVE, FLOOR, NUMBER, NUMBER_OF_BEDS, NEXT_MONTH_PRICE, NEXT_THREE_MONTH_PRICE, NEXT_HALF_YEAR_PRICE, FAST_RESERVE, RATE, RATE_COUNT, HOTEL_COMPANY_ID)
VALUES (2222, 1, 1, 13, 2, 30, 27, 23, 1, 17, 4, 6196);

INSERT INTO ROOM (ID, ACTIVE, FLOOR, NUMBER, NUMBER_OF_BEDS, NEXT_MONTH_PRICE, NEXT_THREE_MONTH_PRICE, NEXT_HALF_YEAR_PRICE, FAST_RESERVE, RATE, RATE_COUNT, HOTEL_COMPANY_ID)
VALUES (3131, 1, 2, 234, 2, 30, 28, 25, 0, 7, 2, 3995);

INSERT INTO HOTEL_ADDITIONAL_SERVICE (ID, ADDITIONAL_SERVICE_TYPE, PRICE, HOTEL_COMPANY_ID, ACTIVE)
VALUES (4567, 0, 15, 6196, 1);
INSERT INTO HOTEL_ADDITIONAL_SERVICE (ID, ADDITIONAL_SERVICE_TYPE, PRICE, HOTEL_COMPANY_ID, ACTIVE)
VALUES (4568, 1, 12, 6196, 1);